# Generated by Django 4.0 on 2021-12-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('effective_due_date', models.CharField(max_length=255)),
                ('link_href', models.CharField(max_length=255)),
                ('past_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_cumulative', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nick_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255)),
                ('index', models.IntegerField()),
                ('charges', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('nubank_id', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('post_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.bill')),
                ('tags', models.ManyToManyField(to='models.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.bill')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.card')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tag', models.CharField(max_length=255)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.bill')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.card'),
        ),
    ]
