# Generated by Django 4.0 on 2021-12-22 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='models.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='models.client'),
        ),
        migrations.AlterField(
            model_name='categorysummary',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorySummary', to='models.bill'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='models.card'),
        ),
        migrations.AlterField(
            model_name='tagsummary',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagSummary', to='models.bill'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='models.bill'),
        ),
    ]
